spring.config.import=optional:classpath:secrets.properties

# Server
server.port=${PORT:8080}

# MySQL Database
spring.datasource.url=jdbc:mysql://bsdexqluo6bxpfivymwu-mysql.services.clever-cloud.com:3306/bsdexqluo6bxpfivymwu?useSSL=true&requireSSL=true&serverTimezone=UTC
spring.datasource.username=u27lilkzqglu0bqv
spring.datasource.password=SILAu2Wptkah63vD4OJe
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Connection Pool
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=120000
spring.datasource.hikari.connection-timeout=20000

# File Upload
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB
file.upload.dir=./uploads

# JWT Secret
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

# Gemini API Key (replace with your key)
gemini.api.key=${GEMINI_KEY}
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-latest:generateContent

# Email Configuration (Gmail SMTP)
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000

# Logging
logging.level.com.smarthire=DEBUG
logging.level.org.springframework.jdbc=DEBUG

# Frontend
frontend.url=${FRONTEND_URL}

# CORS
cors.allowed.origins=https://smart-hire-ats-portal.vercel.app

# OTP Demo Mode
# true  = OTP returned in API response (shown on frontend) - for demo/production
# false = OTP only printed to server console - for local dev
otp.demo.mode=${OTP_DEMO_MODE:true}

spring.autoconfigure.exclude=\
org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration,\
org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration